[package]
name        = "orbital-utils"
version     = { workspace = true }
edition     = { workspace = true }
authors     = ["benskey bekauz@protonmail.com"]
description = "orbital utils"

[lib]

[dependencies]
cosmwasm-schema  = { workspace = true }
cw-storage-plus  = { workspace = true }
neutron-sdk      = { workspace = true }
cosmwasm-std     = { workspace = true }
prost            = { workspace = true }
cw-utils         = { workspace = true }
polytone         = "1.0.0"
sha2             = { workspace = true }
serde-json-wasm  = { workspace = true }
